# Default values for atlas-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: arigaio/atlas-operator
  pullPolicy: IfNotPresent
  tag: ""

rbac:
  create: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true

securityContext:
  runAsUser: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 80

volumes:
  name: certificates-vol
  mountPath: /tmp/certificates
  secretName: cockroachdb.client.root
  secretKey: ca.crt
  secretPath: ca.crt

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
